name: "auth-gocker"

services:
  # PostgresSQL database
  pg:
    container_name: pg
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  # pgAdmin
  pg_admin:
    container_name: db_admin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    volumes:
      - pg_admin_data:/var/lib/pgadmin

volumes:
  pg_data:
    name: db_data
    driver: local
  pg_admin_data:
    name: db_admin_data
    driver: local